### PR TITLE
Add GH Actions workflow for CI

### PR DESCRIPTION
**Pull request by duarten**
### What does this PR do?

The goal is to replace CircleCI with Github Actions. This PR adds the
latter, so CircleCI can be removed in a follow-up.

### Motivation

Mainly not requiring contributors to sign up to CircleCI, but also the ability
to run unit tests on CI, and eventually move to self-hosted runners for more
beefy machines.

### Additional Notes

The repo will need to be configured to require the Github Actions checks instead
of the CircleCI ones.

### Checklist

[] I have added unit tests to the code I am submitting
[] My unit tests cover both failure and success scenarios
[] If applicable, I have discussed my architecture

### CODE REVIEW

**Comment by duarten** [comment]
Having some trouble setting the limits 😰

**Comment by duarten** [comment]
Tests failed with

```
---- executor::placement::test::placement_custom_clone stdout ----
thread 'executor::placement::test::placement_custom_clone' panicked at 'assertion failed: set1.is_empty()', glommio/src/executor/placement/mod.rs:548:9

---- io::dma_file_stream::test::read_wronly_file stdout ----
Glommio currently only supports NVMe-backed volumes formatted with XFS or EXT4. To run poll io-related tests, please set GLOMMIO_TEST_POLLIO_ROOTDIR to a NVMe-backed directory path in your environment.
Poll io tests will not run.
thread 'io::dma_file_stream::test::read_wronly_file' panicked at 'Wrong error', glommio/src/io/dma_file_stream.rs:1849:9

---- io::dma_file_stream::test::write_with_readable_file stdout ----
Glommio currently only supports NVMe-backed volumes formatted with XFS or EXT4. To run poll io-related tests, please set GLOMMIO_TEST_POLLIO_ROOTDIR to a NVMe-backed directory path in your environment.
Poll io tests will not run.
thread 'io::dma_file_stream::test::write_with_readable_file' panicked at 'Wrong error', glommio/src/io/dma_file_stream.rs:1979:9

---- task::tests::ref_count::drop_join_handle_before_completion stdout ----
thread 'unnamed-367' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', glommio/src/task/tests.rs:103:13
thread 'task::tests::ref_count::drop_join_handle_before_completion' panicked at 'called `Result::unwrap()` on an `Err` value: Thread panicked { .. }', glommio/src/task/tests.rs:107:48
```

Not sure how to skip those poll io-related tests? The other failures seem legitimate.

**Review by glommer — APPROVED** [review]

**Comment by glommer** [comment]
Duarte, let me know which ones are passing locally vs failing and we'll tackle them next week

**Comment by duarten** [comment]
The ones that failed on CI also fail locally:

1. executor::placement::test::placement_custom_clone
2. io::dma_file_stream::test::read_wronly_file
3. io::dma_file_stream::test::write_with_readable_file
4. task::tests::ref_count::drop_join_handle_before_completion

I'm looking at 4. currently.

I get more test failures locally, but unsure if it is vagrant related.

**Comment by glommer** [comment]
This one is from @thirstycrow  : 
```
task::tests::ref_count::drop_join_handle_before_completion
```

I didn't notice it failing before because it is behind a feature flag, so pure `cargo test` wouldn't run it.

**Pull request merged**
