### PR TITLE
Fix 261

### LINKED ISSUE #261: Shared channel benchmark fails/hangs with probability
I wrote a benchmark for shared channels, which has a probability to fail with `free(): invalid pointer`:

```
$ cargo +nightly bench --bench shared_channel
    Finished bench [optimized] target(s) in 0.14s
     Running target/release/deps/shared_channel-013a11e62adf9291
Shared channel (size: 10): 877.422145ms, 877.4221ns
Shared channel (size: 100): 387.61481ms, 387.6148ns
free(): invalid pointer
error: process didn't exit successfully: `/project/target/release/deps/shared_channel-013a11e62adf9291 --bench` (signal: 6, SIGABRT: process abort signal)
```

It also has a probability (lower than that of freeing invalid pointer) to hang:
```
$ cargo +nightly bench --bench shared_channel
    Finished bench [optimized] target(s) in 0.02s
     Running target/release/deps/shared_channel-013a11e62adf9291
Shared channel (size: 10): 815.309948ms, 815.30994ns
Shared channel (size: 100): 384.314961ms, 384.31497ns
prod waiting
recv waiting
recv waiting
prod waiting
^C
```

Code for the benchmark:

```rust
use std::time::{Duration, Instant};

use glommio::channels::shared_channel;
use glommio::prelude::*;
use glommio::timer::sleep;

fn main() {
    const RUNS: usize = 1_000_000;

    bench_shared_channel(RUNS, 10);
    bench_shared_channel(RUNS, 100);
    bench_shared_channel(RUNS, 1000);
    bench_shared_channel(RUNS, 10000);
}

fn bench_shared_channel(runs: usize, channel_size: usize) {
    let (sender, receiver) = shared_channel::new_bounded(channel_size);
    let t = Instant::now();

    let producer = LocalExecutorBuilder::new()
        .pin_to_cpu(1)
        .spawn(move || async move {
            let sender = sender.connect();

            let mut timeout = Local::local(async {
                sleep(Duration::from_secs(2)).await;
                println!("prod waiting")
            })
            .detach();

            for i in 0..runs {
                if (i + 1) % 10000 == 0 {
                    timeout.cancel();
                    timeout = Local::local(async {
                        sleep(Duration::from_secs(2)).await;
                        println!("prod waiting")
                    })
                    .detach();
                }
                sender.send(1).await.unwrap();
            }

            timeout.cancel();
        });

    let consumer = LocalExecutorBuilder::new()
        .pin_to_cpu(2)
        .spawn(move || async move {
            let receiver = receiver.connect();

            let mut timeout = Local::local(async {
                sleep(Duration::from_secs(2)).await;
                println!("recv waiting")
            })
            .detach();

            for i in 0..runs {
                if (i + 1) % 10000 == 0 {
                    timeout.cancel();
                    timeout = Local::local(async {
                        sleep(Duration::from_secs(2)).await;
                        println!("recv waiting")
                    })
                    .detach();
                }
                receiver.recv().await.unwrap();
            }

            timeout.cancel();
        });

    producer.unwrap().join().unwrap();
    consumer.unwrap().join().unwrap();

    let label = format!("Shared channel (size: {})", channel_size);
    print_elapsed(label.as_ref(), t, runs);
}

fn print_elapsed(label: &str, start: Instant, runs: usize) {
    let elapsed = start.elapsed();
    let avg = elapsed.as_nanos() as f32 / runs as f32;
    println!("{}: {:?}, {:?}ns", label, elapsed, avg);
}
```

### PR DESCRIPTION
**Pull request by glommer**
### What does this PR do?

Fixes #261.

### Motivation

Honestly, stubbornness. I got this close to quitting and going to live in a farm, planting potatoes, never getting any close to a computer ever again.

### CODE REVIEW

**Comment by gardnervickers** [comment]
@glommer Has the `Build forked pull requests` option been enabled in CircleCI?

**Comment by thirstycrow** [comment]
Got "too many open files" with the following code:

```rust
fn main() {
    for i in 0..10000 {
        println!("==========");
        println!("Round {}", i);
        test_spsc(1);
    }
}
```

```
...
==========
Round 506
==========
Round 507
thread 'unnamed-1015' panicked at 'cannot initialize I/O event notification: Os { code: 24, kind: Other, message: "Too many open files" }', glommio/src/parking.rs:259:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'unnamed-1016' panicked at 'cannot initialize I/O event notification: Os { code: 24, kind: Other, message: "Too many open files" }', glommio/src/parking.rs:259:14
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', glommio/benches/shared_channel.rs:32:19
error: bench failed
```

**Comment by thirstycrow** [comment]
A latest run of the above code hangs at round 492.

**Comment by thirstycrow** [comment]
https://github.com/glommer/glommio/blob/8d768f1313a292047332c75cdcdb0dd83bebde22/glommio/src/channels/spsc_queue.rs#L143

```
            self.shadow_head.set(self.head.load(Ordering::Relaxed));
                                                ~~~~~~~~~~~~~~~~~
                                                Should this be Ordering::Acquire?
```

**Comment by glommer** [comment]
Ok, it is likely that the eventfd files are not being released. It is strange, because we do have a drop implementation that should release them.

About the memory ordering, that code uses cached versions of head and tail to avoid always issuing potentially expensive operations. However I do suspect that this is not doing us any favors and am considering reverting back to a simpler version (this is originally 3rd party code).

**Comment by thirstycrow** [comment]
I tried changing the load ordering from relaxed to acquire, but that does not fix it. 

The hanging problem is quite easy to reproduce on my laptop. With `test_spsc(1)` and `let runs: u32 = 100_000`, the bench never goes beyond 80 rounds.

I found that by removing the `self.notifier.wake_up()`, the bench will always reach round 507. Another solution seems to be adding some statement such as a `println`, between `self.notifier.prepare_to_sleep()` and `if process_remote_channels(wakers) == 0`

```rust
            self.notifier.prepare_to_sleep();
            // println!("hello");  <=== Add a simple print here seems also work
            if process_remote_channels(wakers) == 0 {
                self.link_rings_and_sleep(&mut main_ring, &self.eventfd_src)?;
                self.notifier.wake_up();  <===  // The HANGING problem seems disappeared
                                                // with this line commented out
                consume_rings!(into wakers; lat_ring, poll_ring, main_ring);
            }
```

For the above code to work properly, it is required that a thread to set its notifier memory before processing remote channels and going to sleep. Is it possible that the 2 steps be reversed as result of instruction reordering?

**Comment by glommer** [comment]
Right. This is very clear an issue with the wake ups still, so the memory ordering of the queue should not be affecting us much.

Indeed my suspicions lie in the place you highlighted, so what you claim is possible. However `prepare_to_sleep` stores in the sleep notifier's `memory` with `Release` ordering , and `must_notify()` loads the same variable with `Acquire` ordering. It is my understanding that this should make sure that all writes up until this point are visible.

The idea of that snippet is that first, we must announce and commit that we are going to sleep.
After that, if the other side of the channel is activated `must_notify` will return true so a notification will be sent.

**Comment by glommer** [comment]
maybe what's going on is that the size of the channel is not yet seen as updated. Can you try changing the memory order in `prepare_to_sleep` to `SeqCst` ? I don't think stronger serialization in both the reader and writer should be needed.

**Comment by glommer** [comment]
I just pushed a commit that should fix the eventfd issue so we can get it out of the way.
I can reproduce the issue as well, just not as often as you, apparently. SeqCst definitely helps and using a simplified version of the spsc queue without those cached variables, I am yet to see a hang.

With the cached versions I still see hangs. I will work on it a bit more to make sure this is not because of changed timing.

**Comment by glommer** [comment]
The new version should fix all issues.

**Comment by glommer** [comment]
This has been running for a while for me, plus it actually makes sense that it would hang with the lack of the `membarrier` call. So I am merging this. Happy to reopen if the problems continue.

Thanks a lot for throughly testing this!

**Pull request merged**
