### PR TITLE
chore: fix clippy lints

### PR DESCRIPTION
**Pull request by dignifiedquire**
Clippy is failing currently on nightly CI runs, this should fix it

### CODE REVIEW

**Comment by dignifiedquire** [comment]
``` 
---- executor::test::test_spin stdout ----
thread 'executor::test::test_spin' panicked at 'expected user time on LE is much greater than 50 millisecond', glommio/src/executor/mod.rs:3217:13
```

This seems unrelated, not sure what to do about it.

**Comment by glommer** [comment]
Pulling @vmingchen to take a look as he touched this recently.

@HippoBaro in general, I think CI has been a bit unstable for a while, and that's not great. One of the things I suggest is to pin the nightly version so we're in more control over when those new clippy things will be introduced.

The poor guy's initial patch was all good to begin with =)

**Comment by vmingchen** [comment]
My change was to the `test_no_spin` test, and the failing test in this run is `test_spin`. I just triggered the test to re-run in case it is just flaky.

**Review by vmingchen — APPROVED** [review]
Thanks!

**Comment by vmingchen** [comment]
FYI: The test passed in the re-run.

**Pull request merged**
