### PR TITLE
Fix of order of semaphore waiting queue.

### PR DESCRIPTION
**Pull request by laa**
### What does this PR do?

Before the fix waiting queue was implemented as LIFO instead of FIFO.
Additional code clean up was performed.
Semaphore memory safety was ensured on close.

### Checklist

[] I have added unit tests to the code I am submitting
[x] My unit tests cover both failure and success scenarios
[] If applicable, I have discussed my architecture
[x] The new code I am adding is formatted using `rustfmt`

### CODE REVIEW

**Comment by glommer** [comment]
@laa we should add a test of ordering.
Ordering is indeed important for the semaphore and this was a silent break.

The code itself is good, but please add a commit on top with a test that passes now but would fail without the fix

**Comment by laa** [comment]
Sure, will do a bit later.

**Comment by glommer** [comment]
Since this is currently broken I'll merge the current PR.

the test is still welcome but it can come in a separate one

**Comment by laa** [comment]
@glommer thank you. I will do it for sure.

**Pull request merged**
