### PR TITLE
feat: implement AsyncWrite for &DmaStreamWriter

### LINKED ISSUE #544: Implement `AsyncWrite` for &DmaStreamWriter
Looking at the internals of `DmaStreamWriter` it never requires access to `&mut self`, but unfortunately the methods in `AsyncWrite` do so. Currently it is only implemented for `DmaStreamWriter`, but implementing it for `&DmaStreamWriter` would allow me to write using a read reference only. 

Otherwise I am currently stuck, as I have to put the writer into a `RefCell` and borrow across an await point, in order to actually call `write`, when I only have a read reference.

### PR DESCRIPTION
**Pull request by dignifiedquire**
Closes #544

I had to add another `RefCell` around the `file`, which I am not sure if this is exactly how it should be handled.

### CODE REVIEW

**Comment by glommer** [comment]
I am totally ok with this implementation but I can't merge because the nightly clippy tests are failing.

**Review by glommer — APPROVED** [review]

**Comment by dignifiedquire** [comment]
they seem to be unrelated to my changes, should I file a separate PR for them?

**Comment by glommer** [comment]
if you know what's wrong with those, sure. I haven't had time to look very closely.

Thanks!

**Comment by dignifiedquire** [comment]
https://github.com/DataDog/glommio/pull/549

**Comment by HippoBaro** [comment]
Anything-Nightly in CI should not block us from merging. Nightly builds are informative only. Sorry about that!

**Pull request merged**
