### PR TITLE
prepare for release 0.4.0

### PR DESCRIPTION
**Pull request by glommer**
releases a new version.

### CODE REVIEW

**Comment by bryandmc** [comment]
Are there any outstanding, known bugs? And does that mean you'll cut the release from whatever SHA this produces? if so.. may want to get that joinHandle fix in first.

**Comment by glommer** [comment]
I'd like to release something at a 2 month max cadence, if we have something bigish to show for it.
(I'll do a write up).

In this case, we have the `ScopedTask`, and the initial work on `LocalExecutorPoolBuilder` is good too (although it is very early).

You'll notice that I haven't merged this yet so yeah, might want to bring the join handle fix in.

I am not aware of any other bugs except maybe https://github.com/DataDog/glommio/issues/326

**Review by bryandmc — APPROVED** [review]
Yeah the sleep one is the only one I can find in the issue tracker. So sounds good to me. It's probably wise to have a regular-ish release cadence so might as well start that.

**Review by bryandmc — APPROVED** [review]
I say ship it

**Comment by glommer** [comment]
Thanks for taking a look Bryan!
this is likely landing on crates.io tomorrow.

**Pull request merged**
